import Head from "next/head";
import Image from "next/image";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Header from "../components/Header";
import How from "../components/How";
import Navbar from "../components/Navbar";
import News from "../components/News";
import Offer from "../components/Offer";
import Overview from "../components/Overview";
import Services from "../components/Services";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Navbar />
        <Header />
        <How />
        <Overview />
        <Services />
        <Offer />
        <Contact />
        <News />
        <Footer />
      </>
    </div>
  );
}
